### ISSUE TITLE
Window opens and closes immediately

### ISSUE THREAD

**Issue by BrendanMartin** [pramjeet/peek-a-tab#18]
Not sure if it's because of a new Chrome version, but the app is unusable now. When you use Alt-space the Peek-a-tab window opens and closes immediately.

**Comment by Prid13** [comment]
Glad to know I'm not the only one experiencing this. Here, it opens up, but loses focus and is pushed behind the Chrome window. I manually have to select it in my task bar and click on the search area to be able to use it.

**Comment by Prid13** [comment]
Allright, so I made a temporary solution after trying to locate the problem and fixing it.

Turns out the code used to create the popup window is vanilla JS, and for some reason the new Chrome update likes to close/hide the window IF the file being opened is a local file. For web URLs (like Google, GitHub, etc.), the popup window works just fine.

I discovered that the Chrome Extension API has its own way of creating a popup window, so I tried using that, and it worked! Sadly, passing variables to the created window didn't work, so I had to make a small tweak whereby a GET parameter is passed instead along with the file URL. This is used to highlight the current tab in Peek-a-Tab extension.

I've forked the repo, fixed the bug and made a pull request. Let's see if the developer merges the changes asap. If not, here's my fix: https://github.com/Prid13/peek-a-tab -- you can download the files, enable Developer Mode for Extensions in Chrome, and import the extension if you'd like.

**Comment by pramjeet** [comment]
Thanks @Prid13 for the fix. I have merged it and published new version on chrome store, it should be available in sometime.

**Comment by Prid13** [comment]
Thanks for the quick reply and merge -- I did not expect that. This is amazing :)!

**Comment by pramjeet** [comment]
I was about to restart the work on this from now on and you send the pull request just on time. I am trying to finish the requested features and some features I personally have thought of. @Prid13 , you are always welcome to suggest features and even more welcome to send pull requests :)

**Comment by nunoguedelha** [comment]
Hello @pramjeet , thanks a lot for this amazing extension. I'm actually having again the issue reported here. I'm using Chrome stable 102.0.5005.61 on MacOSX.
I haven't seen any new release since 2019, would there be any planned soon?
Thanks again.

**Comment by Prid13** [comment]
@nunoguedelha regarding new features, I actually worked on some like 1-2 years ago, but sadly never got around to finishing them and now I've just lost track of them 😅 I also remember @pramjeet working on exciting new features a while ago (like 1-2 years ago), but no idea what happened.

**Comment by nunoguedelha** [comment]
Thanks for the info @Prid13 , actually I worked around it by setting `closeOnFocusChange` to `false` in the `DOMContentLoaded` event listener:
https://github.com/pramjeet/peek-a-tab/blob/5d168e7353a1504745fa7162be3608053c0c11f1/app.js#L7-L11

Probably a permanent fix would be to add this parameter to the user interface, but I'm not familiar with that part of the code.
